remote_theme: pages-themes/minimal@v0.2.0
title: Benchary‘s Network
description: 通用 Internet 技术
logo: ./logo.png
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
